"""Portable, deterministic capacity contracts for LLM inference."""

from .adapters import to_llmd_planner_payload, to_scaling_policy_input
from .calculator import capacity_for, what_fits
from .drafts import (
    RecipeDraft,
    StructuralAuditStatus,
    StructuralRecipeAudit,
    UnresolvedFact,
    audit_recipe_draft,
    import_llmd_values,
)
from .importers import (
    ModelManifest,
    VLLMInitializationProfile,
    import_huggingface_manifest,
    import_vllm_benchmark,
    import_vllm_initialization,
    materialize_recipe_draft,
    parse_safetensors_header,
    resolve_huggingface_manifest,
    tensor_element_count_from_safetensors_headers,
)
from .models import (
    CapacityContract,
    ConcurrencyPoint,
    ContractError,
    EvidenceKind,
    EvidenceRecord,
    HardwareInventory,
    HardwareSpec,
    ModelSpec,
    RuntimeVariant,
    ValidationLevel,
    WorkloadProfile,
)
from .recipe import (
    RECIPE_VARIANT_FINGERPRINT_VERSION,
    AuditStatus,
    LLMDRoutingSpec,
    LoadRequirement,
    MeasuredGroupProfile,
    ParallelTopology,
    RecipeAudit,
    ServingRecipe,
    audit_recipe,
)
from .scaling import ScalingRecommendation, recommend_scale

__all__ = [
    "CapacityContract",
    "ConcurrencyPoint",
    "ContractError",
    "EvidenceKind",
    "EvidenceRecord",
    "HardwareInventory",
    "HardwareSpec",
    "ModelSpec",
    "RuntimeVariant",
    "ValidationLevel",
    "capacity_for",
    "what_fits",
    "to_llmd_planner_payload",
    "to_scaling_policy_input",
    "ScalingRecommendation",
    "WorkloadProfile",
    "recommend_scale",
    "AuditStatus",
    "LLMDRoutingSpec",
    "LoadRequirement",
    "MeasuredGroupProfile",
    "ParallelTopology",
    "RecipeAudit",
    "RECIPE_VARIANT_FINGERPRINT_VERSION",
    "ServingRecipe",
    "audit_recipe",
    "RecipeDraft",
    "StructuralAuditStatus",
    "StructuralRecipeAudit",
    "UnresolvedFact",
    "audit_recipe_draft",
    "import_llmd_values",
    "ModelManifest",
    "VLLMInitializationProfile",
    "import_huggingface_manifest",
    "import_vllm_benchmark",
    "import_vllm_initialization",
    "materialize_recipe_draft",
    "parse_safetensors_header",
    "resolve_huggingface_manifest",
    "tensor_element_count_from_safetensors_headers",
]
