"""Portable, deterministic capacity contracts for LLM inference."""

from .adapters import to_llmd_planner_payload, to_scaling_policy_input
from .calculator import capacity_for, what_fits
from .drafts import (
    RecipeDraft,
    StructuralAuditStatus,
    StructuralRecipeAudit,
    UnresolvedFact,
    audit_recipe_draft,
    import_llmd_values,
)
from .importers import (
    IncompleteModelError,
    ModelManifest,
    ModelResolutionDraft,
    VLLMInitializationProfile,
    import_huggingface_manifest,
    import_vllm_benchmark,
    import_vllm_initialization,
    inspect_huggingface_config,
    materialize_recipe_draft,
    parse_safetensors_header,
    resolve_huggingface_manifest,
    resolve_huggingface_model_draft,
    resolve_huggingface_revision,
    tensor_element_count_from_safetensors_headers,
)
from .inventory import (
    MeasurementInventory,
    ProviderInstanceSpec,
    ProviderInventory,
    RuntimeInventory,
    RuntimeOption,
)
from .models import (
    CapacityContract,
    ConcurrencyPoint,
    ContractError,
    EvidenceKind,
    EvidenceRecord,
    HardwareInventory,
    HardwareSpec,
    KVCapacityMode,
    ModelSpec,
    RuntimeKVCapacityPoint,
    RuntimeVariant,
    ValidationLevel,
    WorkloadProfile,
)
from .planner import (
    CandidateStatus,
    CapacityPlan,
    ExplorationResult,
    PlanningObjective,
    ResourceClaim,
    SolverCandidate,
    explore,
    plan,
)
from .recipe import (
    RECIPE_VARIANT_FINGERPRINT_VERSION,
    AuditStatus,
    LLMDRoutingSpec,
    LoadRequirement,
    MeasuredGroupProfile,
    ParallelTopology,
    RecipeAudit,
    ServingRecipe,
    audit_recipe,
)
from .scaling import ScalingRecommendation, recommend_scale
from .schema_catalog import available_schema_versions, load_schema
from .vllm_adapter import SNAPSHOT_SCHEMA_VERSION, import_vllm_runtime_snapshot
from .workflows import ModelPlanningResult, ModelPlanningStatus, plan_huggingface_model

__all__ = [
    "CapacityContract",
    "ConcurrencyPoint",
    "ContractError",
    "EvidenceKind",
    "EvidenceRecord",
    "HardwareInventory",
    "HardwareSpec",
    "KVCapacityMode",
    "ModelSpec",
    "RuntimeKVCapacityPoint",
    "RuntimeVariant",
    "ValidationLevel",
    "capacity_for",
    "what_fits",
    "to_llmd_planner_payload",
    "to_scaling_policy_input",
    "ScalingRecommendation",
    "WorkloadProfile",
    "recommend_scale",
    "available_schema_versions",
    "load_schema",
    "AuditStatus",
    "LLMDRoutingSpec",
    "LoadRequirement",
    "MeasuredGroupProfile",
    "ParallelTopology",
    "RecipeAudit",
    "RECIPE_VARIANT_FINGERPRINT_VERSION",
    "ServingRecipe",
    "audit_recipe",
    "RecipeDraft",
    "StructuralAuditStatus",
    "StructuralRecipeAudit",
    "UnresolvedFact",
    "audit_recipe_draft",
    "import_llmd_values",
    "ModelManifest",
    "IncompleteModelError",
    "ModelResolutionDraft",
    "VLLMInitializationProfile",
    "import_huggingface_manifest",
    "inspect_huggingface_config",
    "import_vllm_benchmark",
    "import_vllm_initialization",
    "materialize_recipe_draft",
    "parse_safetensors_header",
    "resolve_huggingface_manifest",
    "resolve_huggingface_model_draft",
    "resolve_huggingface_revision",
    "tensor_element_count_from_safetensors_headers",
    "ProviderInstanceSpec",
    "ProviderInventory",
    "RuntimeOption",
    "RuntimeInventory",
    "MeasurementInventory",
    "CandidateStatus",
    "PlanningObjective",
    "ResourceClaim",
    "SolverCandidate",
    "ExplorationResult",
    "CapacityPlan",
    "explore",
    "plan",
    "ModelPlanningResult",
    "ModelPlanningStatus",
    "plan_huggingface_model",
    "SNAPSHOT_SCHEMA_VERSION",
    "import_vllm_runtime_snapshot",
]
